### ISSUE TITLE
compiling grbl-sim with cygwin

### ISSUE THREAD

**Issue by thrustin** [grbl/grbl-sim#16]
During compiling with "make new" command I keep getting the following error.

./config.h:28:10: fatal error: ../system.h: No such file or directory
 #include "../system.h"

as well as for
#include "../planner.h"
#include "../settings.h"

Are there missing files? 

Thanks

**Comment by MitchBradley** [comment]
grbl-sim must be installed as a subdirectory of the base grbl code, specifically underneath grbl/grbl

Here is how I did it:

```
git clone https://github.com/gnea/grbl.git
cd grbl/grbl
git clone https://github.com/grbl/grbl-sim.git
```

Note that grbl comes from the "gnea" user (the grbl 1.1 series), while grbl-sim comes from "grbl" (the grbl 0.x series).

After doing that, there are still problems, namely the missing file "system_declares.c".

**Comment by MitchBradley** [comment]
The missing system_declares.c has now been corrected via a pull request by @fsantini 

https://github.com/grbl/grbl-sim/pull/17

**Comment by chamnit** [comment]
Thanks for the confirmation
