### ISSUE TITLE
Is there any release available?

### ISSUE THREAD

**Issue by hansmbakker** [grbl/grbl-sim#19]
Is there anybody who has a working build who could add the binaries as a [release](https://github.com/grbl/grbl-sim/releases)?

It would really lower the barrier of using this if we could avoid having to set up a build environment :)

**Comment by hansmbakker** [comment]
PR #20 offers an automated build.

I created binaries using Azure Pipelines, the result is [drop.zip](https://github.com/grbl/grbl-sim/files/2824869/drop.zip).

**Comment by EdwinMarteZorrilla** [comment]
Hi, I downloaded the Binaries releases for windows. How do I specify the port to which the tool will connect to?

**Comment by hansmbakker** [comment]
I have no idea, it was several years ago that I made the binaries so that others wouldn't need to go through the hassle of compiling etc.

However you're the first who showed interest in them and the repository seems abandoned unfortunately.

Since I'm not using this tool anymore I can't help you with it. Hopefully somebody else can help you.
